### ISSUE TITLE
9Anime Parse Error (wrong cipher)

### ISSUE THREAD

**Issue by rishabhnayak** [saikou-app/saikou#355]
### Summary

9Anime Parse Error (wrong cipher)

### Reproduction Steps

Trying to watch anime

### Expected Result

play anime

### Actual Result

showing error

### Device Information

Android version 10

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Shemar890** [comment]
Need to update the app

**Comment by AdriBD83** [comment]
> Need to update the app

Is update available?

**Comment by rubbean** [comment]
> > Need to update the app
> 
> Is update available?
You'll need to build a new version of Saikou using the source, since this bug has been fixed in main source code

**Comment by Shemar890** [comment]
Need to bluid new update send change anime sites dome want too fix

**Comment by DEVIL7HUNTER** [comment]
still having this problem on 9anime and its backup both not working
