### ISSUE TITLE
Selecting server error

### ISSUE THREAD

**Issue by 3ni0lA** [saikou-app/saikou#667]
![Screenshot_20230502_201208_Saikou ](https://user-images.githubusercontent.com/104868415/235763132-73eec005-cfb9-4639-8fa3-7246aeaebfdb.png)

### Summary

Was trying to watch anime but encountered syntax error 

### Reproduction Steps

Opened saikou b
Clicked on Hells paradise 
Tried selecting server 
Didn't work but showed syntax error 
Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>

### Expected Result

For me to be able to select a server and watch anime

### Actual Result

Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>

### Device Information

Saikou Version: 1.2.0.23
Device: samsung a03
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Kindly get this fixed as soon as possible and lovely app btw

**Comment by Kurukikun** [comment]
Try using vpn it can help you

**Comment by 3ni0lA** [comment]
Ok will do

**Comment by brahmkshatriya** [comment]
Unable to replicate, the error was on website, & probably got fixed by site itself

**Comment by 3ni0lA** [comment]
Tried the vpc still the same error and it hasn't been fixed yet
